import type { Gate, GateRun, Status } from "./types";
import type { Verdict } from "./verdict";

/**
 * Rendering, kept away from both the running and the deciding.
 *
 * There are three audiences and they want different things: a developer at a
 * terminal wants the failing output inline, a pull request wants one summary it
 * can skim, and the gate matrix wants the severities and the reasons for them.
 * All three are derived from the same run, so they cannot disagree.
 */

const MARK: Record<Status, string> = {
  passed: "PASS",
  failed: "FAIL",
  skipped: "SKIP",
};

const COLOUR: Record<Status, string> = {
  passed: "\x1b[32m",
  failed: "\x1b[31m",
  skipped: "\x1b[90m",
};

const RESET = "\x1b[0m";

function duration(ms: number): string {
  return ms >= 1000 ? `${(ms / 1000).toFixed(1)}s` : `${ms}ms`;
}

export function renderTerminal(runs: GateRun[], verdict: Verdict, colour = true): string {
  const paint = (s: Status, text: string) => (colour ? `${COLOUR[s]}${text}${RESET}` : text);
  const lines: string[] = [];

  for (const run of runs) {
    const { status } = run.outcome;
    const tag = run.gate.severity === "reporting" && status === "failed" ? " (reporting only)" : "";
    lines.push(
      `${paint(status, MARK[status])}  ${run.gate.title.padEnd(14)} ${run.outcome.summary}${tag}` +
        (run.durationMs > 0 ? `  ${duration(run.durationMs)}` : ""),
    );
  }

  // Detail goes after the summary block, not inline, so the shape of the run
  // stays readable when several gates have something to say.
  //
  // Any gate with detail, not only the failed ones: a gate can pass and still
  // be carrying a finding it classified as worth reporting, and detail that is
  // printed only on failure would make those findings invisible in exactly the
  // runs where somebody could act on them cheaply.
  for (const run of runs) {
    if (!run.outcome.details) continue;
    lines.push("", `--- ${run.gate.title} ---`, run.outcome.details);
  }

  lines.push("");
  lines.push(
    verdict.passed
      ? paint("passed", `PASSED  ${verdict.counts.passed} gates`)
      : paint(
          "failed",
          `FAILED  ${verdict.blockingFailures.length} blocking ` +
            `(${verdict.blockingFailures.map((r) => r.gate.id).join(", ")})`,
        ),
  );
  if (verdict.reportingFailures.length > 0) {
    lines.push(
      `        ${verdict.reportingFailures.length} reporting finding(s), not blocking: ` +
        verdict.reportingFailures.map((r) => r.gate.id).join(", "),
    );
  }

  return lines.join("\n");
}

/** One comment, not one per gate — the pull request stays readable. */
export function renderMarkdown(runs: GateRun[], verdict: Verdict): string {
  const heading = verdict.passed ? "All blocking gates passed" : "Blocking gates failed";

  const rows = runs.map((run) => {
    const severity = run.outcome.status === "failed" ? run.gate.severity : "";
    return `| ${MARK[run.outcome.status]} | ${run.gate.title} | ${run.outcome.summary} | ${severity} |`;
  });

  const out = [
    `### ${heading}`,
    "",
    "| | Gate | Result | |",
    "|---|---|---|---|",
    ...rows,
  ];

  // Collapsed, and present for anything with detail — see renderTerminal.
  for (const run of runs.filter((r) => r.outcome.details)) {
    out.push(
      "",
      `<details><summary>${run.gate.title} — ${run.outcome.summary}</summary>`,
      "",
      "```",
      run.outcome.details ?? "",
      "```",
      "",
      "</details>",
    );
  }

  if (verdict.reportingFailures.length > 0) {
    out.push(
      "",
      "Reporting-only findings do not block the merge. They are listed so the decision to " +
        "ignore them is a decision someone made, rather than one nobody saw.",
    );
  }

  return out.join("\n");
}

/**
 * The gate matrix, generated rather than written. A hand-maintained table of
 * which gates block would be wrong within a month; this one cannot be, because
 * the severity and the reason for it are read straight off the gate.
 */
export function renderGateMatrix(gates: Gate[]): string {
  return [
    "<!-- Generated by `make gate-matrix`. Edit gates/src/registry.ts, not this file. -->",
    "",
    "# Gate matrix",
    "",
    "Every gate the platform runs, whether it blocks a merge, and why it has the severity it",
    "has. Blocking gates fail the required check. Reporting gates are surfaced on the pull",
    "request and never stop it.",
    "",
    "| Gate | Severity | Why |",
    "|---|---|---|",
    ...gates.map((g) => `| ${g.title} | ${g.severity} | ${g.rationale} |`),
    "",
  ].join("\n");
}
